# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import red

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 70, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 70, 113, 22))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(570, 70, 113, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 420, 611, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hboxlayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.btn_creat = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_creat.setStyleSheet("background-color: rgb(255, 136, 39);")
        self.btn_creat.setObjectName("btn_creat")
        self.hboxlayout.addWidget(self.btn_creat)
        self.btn_rename = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rename.sizePolicy().hasHeightForWidth())
        self.btn_rename.setSizePolicy(sizePolicy)
        self.btn_rename.setStyleSheet("background-color: rgb(255, 136, 39);")
        self.btn_rename.setObjectName("btn_rename")
        self.hboxlayout.addWidget(self.btn_rename)
        self.btn_red = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_red.setStyleSheet("background-color: rgb(255, 136, 39);")
        self.btn_red.setObjectName("btn_red")
        self.hboxlayout.addWidget(self.btn_red)
        self.btn_del = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_del.setStyleSheet("background-color: rgb(255, 136, 39);")
        self.btn_del.setObjectName("btn_del")
        self.hboxlayout.addWidget(self.btn_del)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 50, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 50, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(610, 50, 55, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(80, 100, 631, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(0, 30, 631, 281))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.btn_del)
        MainWindow.setTabOrder(self.btn_del, self.btn_rename)
        MainWindow.setTabOrder(self.btn_rename, self.btn_red)
        MainWindow.setTabOrder(self.btn_red, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.btn_creat)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_creat.setText(_translate("MainWindow", "Создать"))
        self.btn_creat.setShortcut(_translate("MainWindow", "Return"))
        self.btn_rename.setText(_translate("MainWindow", "Переименовать"))
        self.btn_rename.setShortcut(_translate("MainWindow", "Backspace"))
        self.btn_red.setText(_translate("MainWindow", "Редактировать"))
        self.btn_red.setShortcut(_translate("MainWindow", "*"))
        self.btn_del.setText(_translate("MainWindow", "Удалить"))
        self.btn_del.setShortcut(_translate("MainWindow", "Del"))
        self.label.setText(_translate("MainWindow", "Источник"))
        self.label_2.setText(_translate("MainWindow", "Сток"))
        self.label_3.setText(_translate("MainWindow", "Объем"))
        self.groupBox.setTitle(_translate("MainWindow", "Элементы"))


        self.add_function()
    def add_function(self):
        self.btn_creat.clicked.connect(lambda: self.write_number(self.lineEdit.text() + " " + self.lineEdit_2.text() + " " + self.lineEdit_3.text()))



    def write_number(self, txt):
        self.textEdit.append(txt)

            #self.textEdit.setText(self.textEdit.text() + txt)
